//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCBot.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class rand_messages_old
    {
        public long rowid { get; set; }
        public Nullable<long> rowid_irc { get; set; }
        public string kanava { get; set; }
        public string message { get; set; }
        public string initiator { get; set; }
    }
}
