//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class timed_messages
    {
        public long rowid { get; set; }
        public string channel { get; set; }
        public string message { get; set; }
        public Nullable<long> timing_ID { get; set; }
    
        public virtual timing_table timing_table { get; set; }
        public virtual timing_table timing_table1 { get; set; }
    }
}
